workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "PregnancyScanApp.xcodeproj"
        XCODE_SCHEME: "PregnancyScanApp"
        BUNDLE_ID: "com.sjroesink.PregnancyScanApp"
      groups:
        - github_credentials
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          cd $CM_BUILD_DIR
          xcodegen generate

      - name: Show Xcode and SDK info
        script: |
          xcodebuild -version
          xcodebuild -showsdks | grep iphoneos
          xcrun --sdk iphoneos --show-sdk-path

      - name: Build unsigned .app for device
        script: |
          cd $CM_BUILD_DIR
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -configuration Debug \
            -derivedDataPath $CM_BUILD_DIR/build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            SWIFT_ACTIVE_COMPILATION_CONDITIONS='DEBUG' \
            | xcpretty

      - name: Package as unsigned IPA
        script: |
          cd $CM_BUILD_DIR
          APP_PATH=$(find build/Build/Products -name "*.app" -type d | head -1)
          if [ -n "$APP_PATH" ]; then
            echo "Found app: $APP_PATH"
            # Create Payload structure for IPA
            mkdir -p Payload
            cp -r "$APP_PATH" Payload/
            zip -r PregnancyScanApp-unsigned.ipa Payload/
            rm -rf Payload
            echo "Created: PregnancyScanApp-unsigned.ipa"
          else
            echo "ERROR: No .app found"
            exit 1
          fi

    artifacts:
      - build/Build/Products/**/*.app
      - PregnancyScanApp-unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/Logs/Build/*.xcresult

    publishing:
      scripts:
        - name: Create GitHub Release
          script: |
            #!/bin/bash
            set -e

            # Requires GITHUB_TOKEN in environment group 'github_credentials'
            if [ -z "$GITHUB_TOKEN" ]; then
              echo "GITHUB_TOKEN not set — skipping GitHub Release"
              exit 0
            fi

            REPO="sjroesink/PregnancyScanApp"
            TAG="build-${CM_BUILD_ID}"
            COMMIT=$(git rev-parse HEAD)
            SHORT_SHA=$(git rev-parse --short HEAD)
            DATE=$(date +%Y-%m-%d)

            # Create release
            RELEASE_RESPONSE=$(curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              "https://api.github.com/repos/$REPO/releases" \
              -d "{
                \"tag_name\": \"$TAG\",
                \"target_commitish\": \"$COMMIT\",
                \"name\": \"Build $DATE ($SHORT_SHA)\",
                \"body\": \"Unsigned device build from Codemagic.\\n\\nCommit: $SHORT_SHA\\nBuild ID: $CM_BUILD_ID\\n\\n**How to install via Sideloadly (Windows):**\\n1. Download the .ipa file below\\n2. Open Sideloadly on your PC\\n3. Connect your iPhone via USB\\n4. Drag the .ipa into Sideloadly\\n5. Sign in with your Apple ID\\n6. Click Start — Sideloadly will sign and install the app\\n\\n**Note:** Free Apple IDs require re-signing every 7 days. Paid Developer accounts ($99/yr) last 1 year.\",
                \"draft\": false,
                \"prerelease\": true
              }")

            UPLOAD_URL=$(echo "$RELEASE_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['upload_url'].replace('{?name,label}',''))")

            # Upload IPA artifact
            IPA_FILE="$CM_BUILD_DIR/PregnancyScanApp-unsigned.ipa"
            if [ -f "$IPA_FILE" ]; then
              curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                "$UPLOAD_URL?name=PregnancyScanApp-unsigned.ipa" \
                --data-binary @"$IPA_FILE"
              echo "Uploaded to GitHub Release: $TAG"
            else
              echo "No IPA file found to upload"
            fi

  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.sjroesink.PregnancyScanApp
      xcode: latest
      vars:
        XCODE_PROJECT: "PregnancyScanApp.xcodeproj"
        XCODE_SCHEME: "PregnancyScanApp"
        BUNDLE_ID: "com.sjroesink.PregnancyScanApp"
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          cd $CM_BUILD_DIR
          xcodegen generate

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build ipa for distribution
        script: |
          cd $CM_BUILD_DIR
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
