name: PregnancyScanApp

options:
  bundleIdPrefix: com.sjroesink
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"

targets:
  PregnancyScanApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: PregnancyScanApp
        excludes:
          - "**/*.xcassets"
          - "**/Info.plist"
          - "Preview Content/**"

    resources:
      - path: PregnancyScanApp/Resources/Assets.xcassets
      - path: PregnancyScanApp/Preview Content/Preview Assets.xcassets

    info:
      path: PregnancyScanApp/Info.plist
      properties:
        CFBundleDisplayName: "BumpScan 3D"
        CFBundleName: "BumpScan 3D"
        UILaunchScreen: {}

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sjroesink.PregnancyScanApp
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: PregnancyScanApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: iphoneos
        VALID_ARCHS: arm64

      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG ENABLE_OBJECT_CAPTURE
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -Osize
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ENABLE_OBJECT_CAPTURE

    dependencies:
      - sdk: RealityKit.framework
      - sdk: RealityFoundation.framework
      - sdk: ARKit.framework
      - sdk: ModelIO.framework
      - sdk: SceneKit.framework
      - sdk: QuickLook.framework
      - sdk: Observation.framework
      - sdk: SwiftData.framework
      - sdk: Metal.framework
      - sdk: QuartzCore.framework

    entitlements:
      path: PregnancyScanApp/PregnancyScanApp.entitlements

schemes:
  PregnancyScanApp:
    build:
      targets:
        PregnancyScanApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
